// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzCqQj6ZYcROVd0VmD7R6D07rnayzqsBk',
    appId: '1:729743381359:web:b739e3ddd8868492858e9a',
    messagingSenderId: '729743381359',
    projectId: 'cinema-gate-a19e3',
    authDomain: 'cinema-gate-a19e3.firebaseapp.com',
    storageBucket: 'cinema-gate-a19e3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW8IProurqEeeeNWL7HPf0a4Kbd4JvLrQ',
    appId: '1:729743381359:android:f269056daefcadba858e9a',
    messagingSenderId: '729743381359',
    projectId: 'cinema-gate-a19e3',
    storageBucket: 'cinema-gate-a19e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuIwcQ2-bAtVsQN26TKPwKk2_BXBTWwzM',
    appId: '1:729743381359:ios:3784a8dabe2ad35d858e9a',
    messagingSenderId: '729743381359',
    projectId: 'cinema-gate-a19e3',
    storageBucket: 'cinema-gate-a19e3.appspot.com',
    iosClientId:
        '729743381359-paru1ullprl3tsl4fgi0qhnn2r0v0ff8.apps.googleusercontent.com',
    iosBundleId: 'in.example.cinema_gate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuIwcQ2-bAtVsQN26TKPwKk2_BXBTWwzM',
    appId: '1:729743381359:ios:3784a8dabe2ad35d858e9a',
    messagingSenderId: '729743381359',
    projectId: 'cinema-gate-a19e3',
    storageBucket: 'cinema-gate-a19e3.appspot.com',
    iosClientId:
        '729743381359-paru1ullprl3tsl4fgi0qhnn2r0v0ff8.apps.googleusercontent.com',
    iosBundleId: 'in.example.cinema_gate',
  );
}
